CREATE TABLE DEPT (
	DEPTNO INT(2) NOT NULL,
	DNAME VARCHAR,
	LOC VARCHAR,
	PRIMARY KEY(DEPTNO)
);

CREATE TABLE EMP (
	EMPNO INT(2) NOT NULL,
	ENAME VARCHAR,
	JOB VARCHAR,
	HIERDATE DATE,
	MGR INT(2),
	SAL FLOAT(7,2),
	COMM FLOAT(7,2),
	DEPTNO INT(2) NOT NULL,
	PRIMARY KEY(EMPNO),
	FOREIGN KEY(DEPTNO) REFERENCES DEPT(DEPTNO)
);

CREATE TABLE PROJ (
	PROJ_CODE INT(3) NOT NULL,
	DESCRIPTION VARCHAR,
	PRIMARY KEY(PROJ_CODE)
);

CREATE TABLE ASSIGN (
	EMPNO INT(2) NOT NULL,
	PROJ_CODE INT(3),
	A_TIME INT(3),
	PRIMARY KEY(EMPNO, PROJ_CODE),
	FOREIGN KEY(EMPNO) REFERENCES EMP(EMPNO),
	FOREIGN KEY(PROJ_CODE) REFERENCES PROJ(PROJ_CODE)
);

INSERT INTO DEPT VALUES
	(10, 'ACCOUNTING', 'ATHENS'),
	(20, 'SALES', 'LONDON'),
	(30, 'RESEARCH', 'ATHENS'),
	(40, 'PAYROLL', 'LONDON');

INSERT INTO EMP VALUES
	(10, 'CODD', 'ANALYST', '1/1/89', 15, 3000, NULL, 10),
	(15, 'ELMASRI', 'ANALYST', '2/5/95', 15, 1200, 150, 10),
	(20, 'NAVATHE', 'SALESMAN', '7/7/77', 20, 2000, NULL, 20),
	(30, 'DATE', 'PROGRAMMER', '4/5/04', 15, 1800, 200, 10);

INSERT INTO PROJ VALUES
	(100, 'PAYROLL'),
	(200, 'PERSONELL'),
	(300, 'SALES');

INSERT INTO ASSIGN VALUES
	(10, 100, 40),
	(10, 200, 60),
	(15, 100, 100),
	(20, 200, 100),
	(30, 100, 100);

/* Using SQLite3 syntax*/

/* .schema -> DESCRIBE */
.schema
/* Make output pretty */
.header on
.mode column
/* Show contents of every table */
SELECT * FROM DEPT;
SELECT * FROM EMP;
SELECT * FROM PROJ;
SELECT * FROM ASSIGN;


/*
 * Output after execution (`sqlite3 -init new_personnel.sql`):
 *
 * CREATE TABLE DEPT (
 *         DEPTNO INT(2) NOT NULL,
 *         DNAME VARCHAR,
 *         LOC VARCHAR,
 *         PRIMARY KEY(DEPTNO)
 * );
 * CREATE TABLE EMP (
 *         EMPNO INT(2) NOT NULL,
 *         ENAME VARCHAR,
 *         JOB VARCHAR,
 *         HIERDATE DATE,
 *         MGR INT(2),
 *         SAL FLOAT(7,2),
 *         COMM FLOAT(7,2),
 *         DEPTNO INT(2) NOT NULL,
 *         PRIMARY KEY(EMPNO),
 *         FOREIGN KEY(DEPTNO) REFERENCES DEPT(DEPTNO)
 * );
 * CREATE TABLE PROJ (
 *         PROJ_CODE INT(3) NOT NULL,
 *         DESCRIPTION VARCHAR,
 *         PRIMARY KEY(PROJ_CODE)
 * );
 * CREATE TABLE ASSIGN (
 *         EMPNO INT(2) NOT NULL,
 *         PROJ_CODE INT(3),
 *         A_TIME INT(3),
 *         PRIMARY KEY(EMPNO, PROJ_CODE),
 *         FOREIGN KEY(EMPNO) REFERENCES EMP(EMPNO),
 *         FOREIGN KEY(PROJ_CODE) REFERENCES PROJ(PROJ_CODE)
 * );
 * DEPTNO  DNAME       LOC
 * ------  ----------  ------
 * 10      ACCOUNTING  ATHENS
 * 20      SALES       LONDON
 * 30      RESEARCH    ATHENS
 * 40      PAYROLL     LONDON
 * EMPNO  ENAME    JOB         HIERDATE  MGR  SAL     COMM   DEPTNO
 * -----  -------  ----------  --------  ---  ------  -----  ------
 * 10     CODD     ANALYST     1/1/89    15   3000.0         10
 * 15     ELMASRI  ANALYST     2/5/95    15   1200.0  150.0  10
 * 20     NAVATHE  SALESMAN    7/7/77    20   2000.0         20
 * 30     DATE     PROGRAMMER  4/5/04    15   1800.0  200.0  10
 * PROJ_CODE  DESCRIPTION
 * ---------  -----------
 * 100        PAYROLL
 * 200        PERSONELL
 * 300        SALES
 * EMPNO  PROJ_CODE  A_TIME
 * -----  ---------  ------
 * 10     100        40
 * 10     200        60
 * 15     100        100
 * 20     200        100
 * 30     100        100
 */
