#!/bin/sh

main() {
        test $# -eq 4 || usage

        rootdir=${1}
        ndbdirs=${2}
        ndatadirs=${3}
        username=${4}

        test -d "${rootdir}" || err "${rootdir}: no such directory"
        isnumber ${ndbdirs} || err "'${ndbdirs}' is not a number"
        isnumber ${ndatadirs} || err "'${ndatadirs}' is not a number"
        test ! -z "$(grep -w "^${username}" /etc/passwd)" ||
        err "'${username}' is not in /etc/passwd"

        makedirs "dbfolder" ${ndbdirs}
        makedirs "datafolder" ${ndatadirs}
}

usage() {
        echo "usage: ${0##*/} root_dir num_dbdirs num_datadirs username" 1>&2
        exit 1
}

err() {
        echo "${0##*/}: $@" 1>&2
        exit 1
}

isnumber() {
        test ! -z "$(echo "${1}" | grep "^[0-9]\+$")"
}

makedirs() {
        n=${2}
        lastdir=$(ls ${rootdir} | grep "${1}" | sed "s/${1}//g" | sort -V | tail -1)
        test -z ${lastdir} && lastdir=0

        while ! [ $(expr ${n}) = 0 ]; do
                lastdir=$(expr ${lastdir} + 1)
                mkdir "${rootdir}/${1}${lastdir}" &&
                chown ${username}: "${rootdir}/${1}${lastdir}"
                n=$(expr ${n} - 1)
        done 
}

main "$@"
