#!/bin/sh

main() {
        test $# -eq 4 || usage

        rootdir=$1
        ndbdirs=$2
        ndatadirs=$3
        username=$4

        test -d "$rootdir" || err "$rootdir: no such directory"
        isnumber $ndbdirs || err "'$ndbdirs' is not a number"
        isnumber $ndatadirs || err "'$ndatadirs' is not a number"
        test ! -z $(grep "$username" /etc/passwd) || err "'$username' is not in /etc/passwd"
        
        # pending...
}

usage() {
        echo "usage: ${0##*/} [ROOT_DIR] [N_DBDIRS] [N_DATADIRS] [USERNAME]" &&
        exit 1
}

err() {
        echo "${0##*/}: $1" && exit 1
}

isnumber() {
        test ! -z $(echo "$1" | grep "^[0-9]\+$")
}

main "$@"
