#!/bin/sh

emptylnregex="^\ *$"

main() {
        case $1 in
                -a) newentry ;;
                -l) list ;;
                -s) sortcol $2 ;;
                -c) filter $2 ;;
                -d) deleteln $2 $3 ;;
                -n) emptyln ;;
                *) usage ;;
        esac
}

usage() {
        echo "usage: ${0##*/} [-a|-l|-s [COL]|-c [KEYWORD]|-d [KEYWORD [-b|-r]]|-n]"
        echo ""
        echo "options:"
        echo "-a        add a new entry"
        echo "-l        list contents of file"
        echo "-s        sort based on specified column (e.g ${0##*/} -s 3)"
        echo "-c        filter keyword"
        echo "-d        delete lines containing a keyword followed by one of the options below"
        echo "    -b    replace line with an empty line"
        echo "    -r    remove line completely"
        echo "-n        count empty lines and ask if they should be deleted"
}

errempty() {
        test -z "$1" && echo "${0##*/}: expected non-empty string" && exit 1
}

skipempty() {
        grep -v "$emptylnregex"
}

newentry() {
        read -erp "First name: " fname
        errempty "$fname"

        read -erp "Last name: " lname
        errempty "$lname"

        read -erp "Town: " town
        errempty "$town"

        read -erp "Phone number: " phone
        errempty "$phone"

        printf "%s %s %s %s\n" "$fname" "$lname" "$town" "$phone" >> catalog
}

list() {
        nl catalog | skipempty
}

sortcol() {
        errempty "$1"
        sort -k "$1" catalog | skipempty
}

filter() {
        errempty "$1"
        grep "$1" catalog
}

deleteln() {
        errempty "$1"
        errempty "$2"

        case $2 in
                -b) sed -i "s/.*$1.*//" catalog ;;
                -r) sed -i "/$1/d" catalog ;;
        esac
}

emptyln() {
        printf "Empty lines in 'catalog': "
        grep "$emptylnregex" catalog | wc -l
        read -erp "Delete them (y/n)? " del
        test "$del" = "y" && deleteln "$emptylnregex" "-r"
}

main "$@"
