#!/bin/sh

emptylnregex="^\ *$"

main() {
        case ${1} in
                -a) newentry ;;
                -l) list ;;
                -s) sortcol ${2} ;;
                -c) filter ${2} ;;
                -d) deleteln ${2} ${3} ;;
                -n) emptyln ;;
                *) usage ;;
        esac
}

usage() {
        echo "usage: ${0##*/} {-a | -l | -n | -c keyword | -d keyword {-b | -r} | -s col}" 1>&2
        echo "" 1>&2
        echo "options:" 1>&2
        echo "-a        add a new entry" 1>&2
        echo "-l        list contents of file" 1>&2
        echo "-n        count empty lines and ask if they should be deleted" 1>&2
        echo "-c        filter keyword" 1>&2
        echo "-d        delete lines containing a keyword followed by one of the options below" 1>&2
        echo "          -b replaces line with an empty line" 1>&2
        echo "          -r removes line completely" 1>&2
        echo "-s        sort based on specified column (e.g ${0##*/} -s 3)" 1>&2

        exit 1
}

errempty() {
        test ! -z "${1}" || usage
}

skipempty() {
        grep -v "${emptylnregex}"
}

newentry() {
        read -erp "First name: " fname
        errempty "${fname}"

        read -erp "Last name: " lname
        errempty "${lname}"

        read -erp "Town: " town
        errempty "${town}"

        read -erp "Phone number: " phone
        errempty "${phone}"

        printf "%s %s %s %s\n" "${fname}" "${lname}" "${town}" "${phone}" >> catalog
}

list() {
        nl catalog | skipempty
}

sortcol() {
        errempty "${1}"
        sort -k "${1}" catalog | skipempty
}

filter() {
        errempty "${1}"
        grep "${1}" catalog
}

deleteln() {
        errempty "${1}"
        errempty "${2}"

        case ${2} in
                -b) sed -i "s/.*${1}.*//" catalog ;;
                -r) sed -i "/${1}/d" catalog ;;
        esac
}

emptyln() {
        printf "Empty lines in 'catalog': "
        grep "${emptylnregex}" catalog | wc -l
        read -erp "Delete them (y/n)? " del
        test "${del}" = "y" && deleteln "${emptylnregex}" "-r"
}

main "$@"
