#!/bin/sh

# TODO: make error checks: grades: 0 - 100

echo "First names starting with K or N:"
awk '$1 ~ /^K|N/ {print $2, $1}' grades
echo ""

echo "Last names starting with C or L:"
awk '$2 ~ /^C|L/ {print $1, $2}' grades
echo ""

echo "Students with their second grade being > 85:"
awk '{if ($5 > 85 && $5 > 85) print}' grades
echo ""

echo "Students in the humanities:"
awk '{if ($3 == "Theo") print}' grades
echo ""

echo "Average grades:"
awk '{
sum = cnt = 0;
for (i = 4; i <= NF; i++) {
        sum += $i;
        cnt++;
}
print $1, $2, sum / cnt}' grades
echo ""

echo "Students with their third grade being < 70:"
awk 'BEGIN {cnt = 0} {if ($6 < 70) cnt++;} END {print cnt}' grades
echo ""

echo "How many student names end in 'is'?"
awk 'BEGIN {cnt = 0} {if ($2 ~ /is$/) cnt++} END {print cnt}' grades
