#!/bin/sh

main() {
        xread "String: " str
        test -z "${str}" && echo "${0##*/}: give a non-empty string" 1>&2 && exit 1

        xread "File: " file
        test ! -f "${file}" && echo "${0##*/}: ${file}: no such file" 1>&2 && exit 1

        awk "/${str}/ {cnt++} END {print cnt}" ${file}
}

# A portable `read` function with behavior similar to
# `read -erp`.
xread() {
        printf "%s" "${1}" && read -r ${2}
}

# Pass all command line arguments to `main`.
main "$@"
